[package]
name = "webgraph-algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.79", features=["backtrace"]}
dsi-progress-logger = "0.2.3"
rayon = "1.8.1"
stderrlog = "0.6.0"
sux = {git = "https://github.com/vigna/sux-rs"}
webgraph = {git = "https://github.com/vigna/webgraph-rs"}
